# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

  target 'ARtour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ARtour

  target 'ARtourTests' do
  inherit! :search_paths
  # Pods for testing
  end

  target 'ARtourUITests' do
  inherit! :search_paths
  # Pods for testing
  end

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'


end
